[tool.poetry]
name = "Starminder"
version = "21.0.0"
description = "Remind yourself of your GitHub stars"
authors = ["Nik Kantar <nik@nkantar.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyGithub = "^1.55"
python-dotenv = "^0.19.0"
loguru = "^0.5.3"
Jinja2 = "^3.0.1"
mistune = "2.0.0rc1"
boto3 = "^1.18.17"
emoji = "^1.4.2"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.3"
pytest = "^6.2.4"
pytest-watch = "^4.2.0"
black = "^24.3"
mypy = "^0.910"
types-emoji = "^1.2.4"
boto3-stubs = "^1.18.26"
flake8 = "^3.9.2"
pydocstyle = "^6.1.1"
