[tool.poetry]
name = "Starminder"
version = "21.0.0"
description = "Remind yourself of your GitHub stars"
authors = ["Nik Kantar <nik@nkantar.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
