[tool.poetry]
name = "Starminder"
version = "21.0.0"
description = "Remind yourself of your GitHub stars"
authors = ["Nik Kantar <nik@nkantar.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.7"
python-dotenv = "^0.15.0"
cryptography = "^3.4.6"
PyGithub = "^1.54.1"
libsass = "^0.20.1"
django-allauth = "^0.44.0"
tomlkit = "^0.7.0"
mistune = "2.0.0rc1"
boto3 = "^1.17.27"
gunicorn = "^20.0.4"
dj-database-url = "^0.5.0"
psycopg2-binary = "^2.8.6"
whitenoise = "^5.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
bandit = "^1.7.0"
pytest = "^6.2.2"
pydocstyle = "^5.1.1"
mypy = "^0.812"
django-debug-toolbar = "^3.2"
pytest-pythonpath = "^0.7.3"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.11.1"
pytest-watch = "^4.2.0"
django-stubs = "^1.7.0"
pytest-django = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''
/(
  | migrations
)/

'''

[tool.pytest]
python_paths = "starminder"
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.coverage.run]
branch = true
omit = [
  "*/migrations/*",
  "*/urls.py",
]

[tool.coverage.report]
show_missing = false
