[project]
name = "Starminder"
version = "3.0.0"
dependencies = []
requires-python = ">=3.13.1"
authors = [
    {name = "Nik Kantar", email = "nik@nkantar.com" },
]
description = "Remind yourself of your GitHub stars"
readme = "README.md"
license = {file = "LICENSE"}
