# Generated by Django 5.2.7 on 2025-10-10 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "Entrie", "verbose_name_plural": "Entries"},
        ),
    ]
