# Generated by Django 5.2.7 on 2025-10-11 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Reminder",
        ),
        migrations.AlterModelOptions(
            name="reminder",
            options={"verbose_name": "Reminder"},
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="post",
            new_name="reminder",
        ),
    ]
