# Generated by Django 5.2.7 on 2025-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_entry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
