# Generated by Django 5.2.7 on 2025-10-11 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_rename_post_reminder_alter_reminder_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entry",
            new_name="Star",
        ),
        migrations.AlterModelOptions(
            name="star",
            options={"verbose_name": "Star"},
        ),
    ]
