# Generated by Django 5.2.7 on 2025-10-10 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_entry_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "Entry", "verbose_name_plural": "Entries"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post"},
        ),
    ]
