# Generated by Django 5.2.7 on 2025-10-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_star_project_url_alter_star_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="description_temp",
            field=models.TextField(blank=True, null=True),
        ),
    ]
