# Generated by Django 5.2.7 on 2025-10-15 02:11

from django.db import migrations


def copy_description_to_temp(apps, schema_editor):
    Star = apps.get_model("content", "Star")
    for star in Star.objects.all():
        star.description_temp = star.description
        star.save(update_fields=["description_temp"])


def copy_temp_to_description(apps, schema_editor):
    Star = apps.get_model("content", "Star")
    for star in Star.objects.all():
        star.description = star.description_temp
        star.save(update_fields=["description"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_star_description_temp"),
    ]

    operations = [
        migrations.RunPython(copy_description_to_temp, copy_temp_to_description),
    ]
