# Generated by Django 5.2.7 on 2025-10-15 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_copy_description_to_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="star",
            name="description",
        ),
    ]
