# Generated by Django 5.2.7 on 2025-10-15 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_remove_star_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="star",
            old_name="description_temp",
            new_name="description",
        ),
    ]
