# Generated by Django 5.2.7 on 2025-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_rename_description_temp_star_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
