# Generated by Django 5.2.7 on 2026-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_star_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="description_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="star",
            name="name_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="star",
            name="project_url_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
