# Generated by Django 5.2.7 on 2025-11-14 05:37

from django.db import migrations


def populate_star_tokens(apps, schema_editor):
    """Populate token field with user's first social token."""
    Star = apps.get_model("content", "Star")
    SocialToken = apps.get_model("socialaccount", "SocialToken")

    for star in Star.objects.filter(token__isnull=True).select_related("reminder"):
        # Get the first social token for this star's user (via reminder)
        first_token = SocialToken.objects.filter(
            account__user=star.reminder.user
        ).first()

        if first_token:
            star.token = first_token
            star.save(update_fields=["token"])


def reverse_populate(apps, schema_editor):
    """Reverse migration - set all tokens to null."""
    Star = apps.get_model("content", "Star")
    Star.objects.all().update(token=None)


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_star_token"),
        ("socialaccount", "__latest__"),
    ]

    operations = [
        migrations.RunPython(populate_star_tokens, reverse_populate),
    ]
