# Generated by Django 3.1.7 on 2021-03-07 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210306_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='html',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
