# Generated by Django 3.1.7 on 2021-03-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210307_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='html',
        ),
    ]
