# Generated by Django 5.2.7 on 2025-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempstar",
            name="project_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="tempstar",
            name="repo_url",
            field=models.URLField(max_length=1024),
        ),
    ]
