# Generated by Django 5.2.7 on 2025-10-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0002_alter_tempstar_project_url_alter_tempstar_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempstar",
            name="description_temp",
            field=models.TextField(blank=True, null=True),
        ),
    ]
