# Generated by Django 5.2.7 on 2025-10-15 02:11

from django.db import migrations


def copy_description_to_temp(apps, schema_editor):
    TempStar = apps.get_model("implementations", "TempStar")
    for tempstar in TempStar.objects.all():
        tempstar.description_temp = tempstar.description
        tempstar.save(update_fields=["description_temp"])


def copy_temp_to_description(apps, schema_editor):
    TempStar = apps.get_model("implementations", "TempStar")
    for tempstar in TempStar.objects.all():
        tempstar.description = tempstar.description_temp
        tempstar.save(update_fields=["description"])


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0003_tempstar_description_temp"),
    ]

    operations = [
        migrations.RunPython(copy_description_to_temp, copy_temp_to_description),
    ]
