# Generated by Django 5.2.7 on 2025-10-15 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0005_remove_tempstar_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tempstar",
            old_name="description_temp",
            new_name="description",
        ),
    ]
