# Generated by Django 5.2.7 on 2025-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0006_rename_description_temp_tempstar_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempstar",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
