# Generated by Django 5.2.7 on 2025-11-14 05:34

from django.db import migrations


def populate_tempstar_tokens(apps, schema_editor):
    """Populate token field with user's first social token."""
    TempStar = apps.get_model("implementations", "TempStar")
    SocialToken = apps.get_model("socialaccount", "SocialToken")

    for temp_star in TempStar.objects.filter(token__isnull=True):
        # Get the first social token for this user
        first_token = SocialToken.objects.filter(account__user=temp_star.user).first()

        if first_token:
            temp_star.token = first_token
            temp_star.save(update_fields=["token"])


def reverse_populate(apps, schema_editor):
    """Reverse migration - set all tokens to null."""
    TempStar = apps.get_model("implementations", "TempStar")
    TempStar.objects.all().update(token=None)


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0008_tempstar_token"),
        ("socialaccount", "__latest__"),
    ]

    operations = [
        migrations.RunPython(populate_tempstar_tokens, reverse_populate),
    ]
