# Generated by Django 5.2.7 on 2025-11-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("implementations", "0009_populate_tempstar_token"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempstar",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="socialaccount.socialtoken",
            ),
        ),
    ]
