# Generated by Django 5.2.7 on 2025-10-10 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
