# Generated by Django 5.2.7 on 2025-10-10 04:42

import uuid
from django.db import migrations, models


def generate_feed_ids(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.feed_id = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_userprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="feed_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(generate_feed_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="feed_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
