# Generated by Django 5.2.7 on 2025-10-11 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_set_default_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="max_entries",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
