# Generated by Django 5.2.7 on 2025-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_userprofile_max_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reminder_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
