# Generated by Django 5.2.7 on 2025-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userprofile_feed_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Custom User"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "User Profile"},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="max_entries",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
