# Generated by Django 5.2.7 on 2025-10-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_customuser_options_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (-1, "day"),
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=-1,
            ),
        ),
    ]
