# Generated by Django 5.1.5 on 2025-01-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_userprofile_created_at_userprofile_modified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                            ("day", "Day"),
                        ],
                        default="day",
                        max_length=9,
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        choices=[
                            (0, "Zero"),
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (9, "Nine"),
                            (10, "Ten"),
                            (11, "Eleven"),
                            (12, "Twelve"),
                            (13, "Thirteen"),
                            (14, "Fourteen"),
                            (15, "Fifteen"),
                            (16, "Sixteen"),
                            (17, "Seventeen"),
                            (18, "Eighteen"),
                            (19, "Nineteen"),
                            (20, "Twenty"),
                            (21, "Twentyone"),
                            (22, "Twentytwo"),
                            (23, "Twentythree"),
                        ],
                        default=0,
                    ),
                ),
                ("maximum", models.PositiveIntegerField(default=5)),
                ("active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
