# Generated by Django 5.2.7 on 2025-10-10 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_userprofile_day_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hour_of_day",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
    ]
