# Generated by Django 5.2.7 on 2025-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_userprofile_max_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="include_archived",
            field=models.BooleanField(default=True),
        ),
    ]
