# Generated by Django 5.2.7 on 2025-10-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_rename_description_temp_star_description"),
        ("core", "0005_alter_userprofile_max_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cycle_start",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.star",
            ),
        ),
    ]
