# Generated by Django 5.2.7 on 2025-11-02 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_star_archived"),
        ("core", "0006_userprofile_include_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cycle_start",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.star",
            ),
        ),
    ]
