# Generated by Django 5.1.5 on 2025-02-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_active_userprofile_day_userprofile_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
    ]
