# Generated by Django 5.2.7 on 2025-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_userprofile_cycle_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
