# Generated by Django 5.1.5 on 2025-02-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userprofile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hour',
        ),
    ]
