# Generated by Django 5.2.7 on 2026-05-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_userprofile_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="include_own",
            field=models.BooleanField(default=True),
        ),
    ]
