# Generated by Django 6.0.6 on 2026-07-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_userprofile_include_own"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="include_contributed",
            field=models.BooleanField(default=True),
        ),
    ]
