name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - uses: taiki-e/install-action@just

    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Check formatting via ruff
      run: uv run just formatcheck

    - name: Check type hints via mypy
      run: uv run just typecheck

    - name: Run linter via ruff
      run: uv run just lint

    - name: Run tests via pytest
      run: uv run just test
