name: Run Starminder
on:
  schedule:
    # Adjust this to your liking
    - cron: "13 10 * * *"
jobs:
  build:
    name: Run Starminder Script
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-dev --no-root --no-interaction
          [ -f requirements.txt ] && poetry run pip install -r requirements.txt

      - name: Run script
        env:
          STARMINDER_COUNT: ${{ secrets.STARMINDER_COUNT }}
          STARMINDER_RECIPIENT: ${{ secrets.STARMINDER_RECIPIENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_FROM: ${{ secrets.AWS_FROM }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          make run
