name: Run Starminder
on:
  schedule:
    - cron: "6 20 * * *"
  push:
    branches: [ main ]
jobs:
  build:
    name: Run Starminder Script
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction

      - name: Run script
        env:
          STARMINDER_COUNT: ${{ secrets.STARMINDER_COUNT }}
          STARMINDER_RECIPIENT: ${{ secrets.STARMINDER_RECIPIENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_FROM: ${{ secrets.AWS_FROM }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_FORK_URL: ${{ secrets.GITHUB_FORK_URL }}
        run: |
          make run
